config/routes.rb
Rails.application.routes.draw do
  resources :productos
    get 'errores/rutas'

    root:to => 'home#index'

    get 'home/index'

    get 'home/quienes_somos'

    get 'home/contacto'

    get 'home/localizacion'

    get 'home/servicios'

    get 'productos/index'

    post 'home/servicios'

    post 'home/contacto'

    match "productos" => "productos#index", :via => [:get, :post]

    match "servicios" => "home#index", :via => [:get, :post]

    match "quienes" => "home#quienes_somos", :as => "quien", :via => [:get]

    match "servicios/:id" => "home#index", :via => [:get, :post], :as => "servicio"

    match "*a" => "errores#rutas", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    attr_accessor :nombre, :apellidos, :edad
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :contador_de_peteciones

  private

  def contador_de_peteciones
      if action_name == "index"
          valor = (cookies[:peticiones] ||= "0").to_i
          cookies[:peticiones] = (valor + 1).to_s
          @peticiones = cookies[:peticiones]
      end
  end
end

app/controllers/errores_controller.rb
class ErroresController < ApplicationController
  def rutas
      render :file => "#{Rails.root}/public/404.html", :layout => false
  end
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController
    around_action :autorizacion
    #@lol = true
    #@xd = false
    Nombres.initialize
    def index
        @titulo = "Estamos en la página principal"
        #@personas = ["Juan", "Ivan", "Lidia"]
        #respond_to do |formato|
        #    formato.html
        #    formato.json { render :json => @personas}
        #    formato.xml {render :xml => @personas}
        #end
        #redirect_to :action => "quienes_somos", :id => ["Bruno", "Adrian", "Atena"], :personas => @personas
        @elementos = Nombres.obtener
        logger.info("Estamos en #{action_name}")
    end

    def quienes_somos
        #@nombre = params[:id]
        @titulo = "Apartado quienes_somos"
    end

    def contacto
        @titulo = "Esto es el apartado de contactos"
        @help = "Edad"
        if request.post?
            #Enviar con todo y datos :v
            begin
                if EmailMailer.micorreo(params).deliver and EmailMailer.enviar(params).deliver
                    flash[:mensaje] = "Enviado correctamente"
                end
                redirect_to :action => "index"
            rescue
                flash[:mensaje] = "No se ha podido enviar"
                redirect_to :action => "index"
            end
        end
        logger.debug("Array #{@array.inspect}")
    end

    def localizacion
        @titulo = "Curso Rails - Localización"
    end

    def servicios
        if request.get?
            @titulo = "Curso Rails - Servicios - GET"
        else
            @titulo = "Curso Rails - Servicios - POST - #{params[:id]}"
            @valor = params[:valor]
        end
        if request.post?
            Nombres.agregar=(params[:Nombre])
            if imagen = params[:archivo]
                nombre_imagen = imagen.original_filename
                directorio = "/home/bruno/Escritorio/" + nombre_imagen
                File.open(directorio, "wb"){|f| f.write(imagen.read)}
            end
            redirect_to root_path
        else
            if params[:Nombre]
                render :inline => (Nombres.obtener.include?(params[:Nombre])) ? "Si" : "No"
            end
        end
    end

    def verificar_datos
        redirect_to "index"
    end

    def autorizacion
        yield
        logger.info("Esto es un filtro")
    end
end

app/controllers/nombres.rb
class Nombres
        def self.initialize
            @@array ||= ["Luis", "Adrian", "Pepe"]
        end

        def self.agregar=(nombre)
            @@array<<nombre
        end

        def self.borrar(nombre)
            @@array.delete(nombre)
        end

        def self.obtener
            @@array
        end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errores_helper.rb
module ErroresHelper
end

app/helpers/home_helper.rb
module HomeHelper

    def enlace(nombre, accion)
        link_to nombre, :action => accion
    end

    def hay_banner?
        if content_for?(:imagen)
            return true
        end
    end

    def es_inicio?
        if action_name == "index"
            return true
        end
    end

    def entrada_de_texto(mensaje)
        entrada = label_tag mensaje, "Inserte su #{mensaje}", :id => "#{mensaje}_x"
        entrada += text_field_tag mensaje
        return entrada
    end

    def radio_buton(cuantos, etiqueta, mensaje)
        radio = "<div class='row'><div class='col s12 l3'>"
        div_ = "</div>"
        for i in(0...cuantos)
            if i == 0
                rad = radio_button_tag :"#{etiqueta}", mensaje[i], true, class: "with-gap"
            else
                rad = radio_button_tag :"#{etiqueta}", mensaje[i], false, class: "with-gap"
            end
            lab = label_tag :"#{etiqueta}_#{mensaje[i]}", "#{mensaje[i].capitalize}"
            radio += '<p>'
            radio += rad + lab
            radio += '</p>'
        end
        radio += div_ + div_
        return radio.html_safe
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/errores/rutas.html.erb
<h1>Errores#rutas</h1>
<p>Find me in app/views/errores/rutas.html.erb</p>

app/views/home/contacto.html.erb
<div class="row">
    <div class="col s12 m6 l4">
        <div class="card center">
            <h3>Contacto</h3>
        </div>
    </div>
</div>
<% if flash[:mensaje] %>
    <script type="text/javascript">
        window.alert(flash[:mensaje])
    </script>
<% end %>
<div class="container">
    <%= form_tag "/home/contacto" do%>
        <div class="card-panel">
            <div class="row">
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= entrada_de_texto "nombre"%>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= entrada_de_texto "apellidos" %>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= label_tag "edad", "Inserte su edad" %>
                    <%= number_field_tag "#{@help.downcase}", nil, in: 1..99 %>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= entrada_de_texto "telefono" %>
                </div>
                <div class="col s12 m6 l6 offset-l3">
                    <%= radio_buton 3, "estado_civil", ["soltero","casado","separado"]%>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= label_tag "email", "Inserte su email" %>
                    <%= email_field_tag "email" %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6 l6 offset-l3">
                    <center>
                        <%= submit_tag "Confirmar", :class => "btn" %>
                    </center>
                </div>
            </div>
        </div>
    <% end %>
</div>
<%= @titulo %><br>
<br>
<%= enlace "Inicio", "index" %>
<script type="text/javascript">
    $("#telefono_x").append("(10 dígitos)")
</script>

app/views/home/index.html.erb
<% if flash[:mensaje] %>
<script type="text/javascript">
    var mensaje = "<%= flash[:mensaje] %>"
    Materialize.toast(mensaje, 4000, 'rounded') // 4000 is the duration of the toast
</script>
<% end %>
<div class="row">
    <div class="col s12">
        <div class="card center">
            <h3>
                <%= @titulo %>
            </h3>
        </div>
    </div>
</div>
<%= button_to "Enviar", {:controller => "home", :action => "servicios"}, :class => "btn blue lighten-3 black-text" %><br>
<%= button_to "Valor", {:controller => "home", :action => "servicios"}, :valor => 20, :class => "btn blue lighten-3 black-text" %>
<div class="row">
    <div class="col s12 m6">
        <div class="card center">
            <h3>Formulario básico</h3>
        </div>
    </div>
</div>
<%= form_tag "/home/servicios", multipart: true do%>
    <div class="row">
        <div class="input-field col s12 l4">
            <%= label_tag "Nombre"%>
            <%= text_field_tag "Nombre"%><br>
        </div>
    </div>
    <div class="row">
        <div class="range-field col s12 m6">
            <%= range_field_tag :rango, 5, :min => 0, :max => 10 %>
        </div>
    </div>
    <p>
        <%= radio_button_tag :edad, "mayor", :checked => true, :class => "with-gap" %>
        <%= label_tag :edad_mayor, "Mayor" %>
    </p>
    <p>
        <%= radio_button_tag :edad, "menor"%>
        <%= label_tag :edad_menor, "Menor"%>
    </p>
    <p>
        <%= check_box_tag :fumador, "si"%>
        <%= label_tag :fumador%>
    </p>
    <%= file_field_tag :archivo %><br><br>
    <%= submit_tag "Enviar", :class => "btn blue lighten-3 black-text"%>
<% end %>
<div class="row">
    <div class="col s12">
        <div class="card center">
            <h3>Formulario de búsqueda por método get</h3>
        </div>
    </div>
</div>
<%= form_tag "/home/servicios", :method => "get" do%>
    <div class="row">
        <div class="input-field col s12 m6 l3">
            <%= label_tag "Nombre"%>
            <%= text_field_tag "Nombre"%>
        </div>
    </div>
    <%= submit_tag "Buscar", :class => "btn blue lighten-3 black-text"%>
<% end %>
<div class="row">
    <div class="col s12 m6 l6">
        <div class="card center">
            <div class="card-content">
                <span class="card-title"><h4>Listado de elementos</h4></span>
                <p>
                    <%for i in(0...@elementos.size) %>
                        <%= @elementos[i] %><br>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/home/localizacion.html.erb
<% content_for :imagen do%>
    <div class="row">
        <div class="col s12 m10 l10 offset-m1 offset-l1">
            <%= image_tag("goku.jpg", :class => "responsive-img")%>
        </div>
    </div>
<% end %>
<div class="row">
    <div class="col s12 m6 l8">
        <div class="card center">
            <h3><%= @titulo %></h3>
        </div>
    </div>
</div>
<div class="container">
    <%= form_tag "/home/contacto" do%>
        <div class="card-panel">
            <div class="row">
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= entrada_de_texto "nombre"%>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= label_tag "email", "Inserte su email" %>
                    <%= email_field_tag "email" %>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= entrada_de_texto "asunto"%>
                </div>
                <div class="input-field col s12 m6 l6 offset-l3">
                    <%= text_area_tag "mensaje", nil %>
                    <%= label_tag "mensaje", "Mensaje" %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6 l6 offset-l3">
                    <center>
                        <%= submit_tag "Confirmar", :class => "btn" %>
                    </center>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/home/quienes_somos.html.erb
<h1>Quienes_somos</h1>
<%= @titulo %><br>

app/views/home/servicios.html.erb
<h1><%= @titulo %></h1>
<p><%= @valor %></p>
<%= image_tag("logo.png", :size => "150x150") %>

app/views/layouts/_cabecera_inicio.html.erb
<div class="container">
    <div class="col s12 l10 offset-l1">
        <div class="card-panel">
            <div class="row">
                <div class="col s12 l6 center">
                    <span><h3>Curso Rails</h3></span>
                    <strong class="center">Do it by Bruno</strong><br><br>
                    <%= button_to "Entrar",{:action => "quienes_somos"}, :class => "btn"%><br><br>
                </div>
                <div class="col s12 l6 center">
                    <%= image_tag("gravitacionales.jpg", :class => "responsive-img", :height => "70%") %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CursoRails</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CursoRails</title>
    <link rel="shortcut icon" href="assets/logo.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.js', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <ul id="slide-out" class="side-nav fixed collapsible">
        <li>
            <%= link_to :action => "index" do%>
                <%= material_icon.home %><span>Inicio</span>
            <% end %>
        </li>
        <li>
            <%= link_to :action => "quienes_somos" do%>
                <%= material_icon.face %><span>¿Quienes somos?</span>
            <% end %>
        </li>
        <li>
            <%= link_to :action => "contacto" do%>
                <%= material_icon.email %>
                <span>Contáctanos</span>
            <% end %>
        </li>
        <li>
            <%= link_to :action => "localizacion" do%>
                <%= material_icon.location_on %><span>Localización</span>
            <% end %>
        </li>
        <li>
            <%= link_to :controller => "home", :action => "servicios" do%>
                <%= material_icon.mood %><span>Servicios</span>
            <% end %>
        </li>
    </ul>
    <nav class="hide-on-large-only blue-grey lighten-2">
        <div class="nav-wrapper">
            <%= link_to 'Curso Rails', {:action => "index"}, :class => "brand-logo right"%>
            <a data-activates="slide-out" class="button-collapse left"><i class="material-icons">menu</i></a>
        </div>
    </nav>
    <main>
        <% if es_inicio? %>
        <h3>No inventes llevas <%= @peticiones %> veces que entras</h3>
        <div class="row">
            <div class="col s10 m8 l6 offset-s1 offset-m2 offset-l3">
                    <div class="card center">
                        <h2>Curso Rails</h2>
                    </div>
            </div>
        </div>
        <% end %>
        <% if hay_banner? %>
            <%= yield :imagen %>
        <% elsif es_inicio? %>
            <%= render "layouts/cabecera_inicio" %>
        <% end %>
        <%= yield %>
    </main>
</body>
<script type="text/javascript">
    $(".button-collapse").sideNav();
</script>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :producto_nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio, id: :producto_precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>